### ISSUE TITLE
urllib2.HTTPError: HTTP Error 520: Origin Error

### ISSUE THREAD

**Issue by crazygeekone** [matveyco/cex.io-api-python#12]
hi my python script close some times with this error : 

Traceback (most recent call last):
  File "start.py", line 82, in <module>
    data = api.balance()
  File "/usr/local/lib/python2.7/dist-packages/cexapi-0.1-py2.7.egg/cexapi/cexapi.py", line 66, in balance
    return self.api_call('balance', {}, 1)
  File "/usr/local/lib/python2.7/dist-packages/cexapi-0.1-py2.7.egg/cexapi/cexapi.py", line 53, in api_call
    answer = self.__post(url, param)  # Post Request
  File "/usr/local/lib/python2.7/dist-packages/cexapi-0.1-py2.7.egg/cexapi/cexapi.py", line 40, in __post
    page = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 520: Origin Error

Can you have a look ?
Thanks.

**Comment by whbdupree** [comment]
Did you resolve this? I am seeing this sometimes.

**Comment by notanewbie** [comment]
Yeah same here
